PROOT_NO_SECCOMP=1 $HOME/udocker/udocker run --user=root -v $(pwd):/app merimpytorch python3 train_gain_pytorch_discriminator_same_info_as_gen.py --data_name faulty_training --batch_size 512 --folder_name 2
